spring:
  application:
    name: JwtValidator-Service
  profiles:
    active: dev
  config:
    import: application-prod.yml
  messages:
    basename: messages
    encoding: UTF-8
server:
  port: 9050
    
jwt:
  secret: 5367566B5970337336762342342342341139792F4123F452811482B4D6251655468576D5A71347437


otel:
  service:
    name: "auth-service"
  traces:
    exporter: "otlp"
    sampler: "always_on"
  metrics:
    exporter: "otlp"
    export:
      interval: 5000
  logs:
    exporter: "otlp"
  exporter:
    otlp:
      protocol: "grpc"
      endpoint: "http://localhost:4317"
